{% set version = "1.2.4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rentrez
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rentrez_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rentrez/rentrez_{{ version }}.tar.gz
  sha256: 22dda569f264128b5e86aa0ed6e9a5a11e489bbc01ac55300a272c8cd233e180

build:
  number: 1
  noarch: generic
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-xml
    - r-httr >=0.5
    - r-jsonlite >=0.9
  run:
    - r-base
    - r-xml
    - r-httr >=0.5
    - r-jsonlite >=0.9

test:
  commands:
    - $R -e "library('rentrez')"           # [not win]
    - "\"%R%\" -e \"library('rentrez')\""  # [win]

about:
  home: http://github.com/ropensci/rentrez
  license: MIT
  license_file: LICENSE
  summary: Provides an R interface to the NCBI's 'EUtils' API,  allowing users to search databases like 'GenBank'  <https://www.ncbi.nlm.nih.gov/genbank/> and 'PubMed'  <https://www.ncbi.nlm.nih.gov/pubmed/>, process the  results of those searches and pull data into their R sessions.
  license_family: MIT

extra:
  recipe-maintainers:
    - ocefpaf
    - conda-forge/r

# Package: rentrez
# Version: 1.2.2
# Date: 2019-05-02
# Title: 'Entrez' in R
# Authors@R: c( person("David", "Winter", role=c("aut", "cre"),  email = "david.winter@gmail.com",  comment = c(ORCID = "0000-0002-6165-0029")), person("Scott", "Chamberlain", role="ctb", email = "myrmecocystus@gmail.com", comment = c(ORCID = "0000-0003-1444-9135")), person("Han","Guangchun", role=c("ctb"),email="hanguangchun@gmail.com", comment = c(ORCID = "0000-0001-9277-2507")) )
# Depends: R (>= 2.6.0)
# Imports: XML, httr (>= 0.5), jsonlite (>= 0.9)
# Suggests: testthat, knitr, rmarkdown
# URL: http://github.com/ropensci/rentrez
# BugReports: https://github.com/ropensci/rentrez/issues
# Description: Provides an R interface to the NCBI's 'EUtils' API,  allowing users to search databases like 'GenBank'  <https://www.ncbi.nlm.nih.gov/genbank/> and 'PubMed'  <https://www.ncbi.nlm.nih.gov/pubmed/>, process the  results of those searches and pull data into their R sessions.
# VignetteBuilder: knitr
# License: MIT + file LICENSE
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2019-05-02 01:43:03 UTC; david
# Author: David Winter [aut, cre] (<https://orcid.org/0000-0002-6165-0029>), Scott Chamberlain [ctb] (<https://orcid.org/0000-0003-1444-9135>), Han Guangchun [ctb] (<https://orcid.org/0000-0001-9277-2507>)
# Maintainer: David Winter <david.winter@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-05-02 11:50:06 UTC
