appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: GU0qn2Cc8lMmIzpU8V7+g82ueLQT/wJyAV7TEuW+HSonMjGPGf83z7+DsaD2ybzgIgsslHAdAf2eioCP5E9jNkYLN492nA7ZaWlLDRLbDmMAImIwC11Rpgn9NLBlmQbDYu/fN4P0NCK9KZ/p9+GiWDEOFl+2KsnW7z6z1puPKPx2CXitoXmlU8R7C+Z1OED44i8oho1dz5gMlNy2KFe/55tIBeZNWontMsNsfPcU4XQtiH5nnDO8GVsvqgF2Zg7OF0adLg6GcLflsUemuCtoZywBo+DwEoSoFbKP05E4652Adyq8hNhHlWGckZER1g+4yVnh7ZWCJyaJMN6kQWbExId1aoUJPAziNWWqivdkQdxQKk5Yo5j/FpewSgG8FMaU/4nPZ0SB0d0fyiiN21clsaEQTtjhlf4bhjM6r4XZHirzqDcSTkrrQcmf4H0C7/sBlnSuQ/xD9pAFPKAy84RH3vzxeSPNuxFE3xGwNGBIGfNVGpNBQ5LAe12jLDTszvh0Nt0GKK7Yp7sD3Ai1nNSnhCfNA9uyD0rOpeF8ptfBRqj0lpQ6WAiDCn24f8WEYEu5Keyr1QuwBwMkQSTI5gqfX3Po4qM1Xzb3E2gwmW7xQ8wT591kbcTtsqwzolDoizvHbRK1e+xqAK7mLdKtWEHHg3XalvfBJ6oca9TUG6YLY/E=}
bot:
  automerge: true
